### ISSUE TITLE
Rename the github project l2t_scaffolder

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/L2tScaffolder#43]
Since this is not only for plaso development, rename the project into l2t_scaffolder.

1. Create a PR that renames plasoscaffolder to l2tscaffolder in every file and rename directory.
2. Rename the github project
3. Create a release
4. Push the new version to pypi.

This is all dependent on:

+ https://github.com/log2timeline/PlasoScaffolder/pull/40: New frontend
+ https://github.com/log2timeline/PlasoScaffolder/pull/42: Deleting/removing old code

These dependencies need to be checked in first.

**Comment by Onager** [comment]
Rather than rename the project, why not move this to l2tdevtools? That's what we'd discussed earlier.

**Comment by kiddinn** [comment]
This is the first step, to rename the project, the move to l2tdevtools was somewhat dependent on python3 readiness of that tool

**Comment by kiddinn** [comment]
This is done, I'll create a new issue to track migration to l2tdevtools
